export const centralizacionUrl :string= "https://sac.digitalware.co:442/Seven_Crm/Centralizacion/api/";
export const appVersion:string = '21.0.2.0';
export const appCopyright = 'SEVEN-ERP © 1992-2021';
export const appGooglePlayUrl = "";
export const appAppStoreUrl = "";
export const developer = 'DigitalWare Team';
export const developerMail = 'soporte@digitalware.com.co';
export const developerFacebook = 'https://www.facebook.com/digitalware/';
export const developerTwitter = 'https://twitter.com/Digital_Ware';
export const developerWeb = 'http://www.digitalware.com.co/';
export const developerMode = true;
export const developerUrl="http://cerezo/REST/SQL/RSEVSERV/api/"
